Repository lablup/backend.ai-manager, pull requests merged in 2019-09, with the labels that each got.

#187 Support for shared memory option in creating compute session
  alembic/versions/5b45f28d2cac_add_resource_opts_in_kernels.py
  src/ai/backend/gateway/kernel.py
  src/ai/backend/gateway/resource.py
  src/ai/backend/manager/models/kernel.py
  src/ai/backend/manager/registry.py
Labels: API

#191 Let user domain can be updated by superadmin
  src/ai/backend/manager/models/user.py
Labels: API, minor

#192 Job queueing
  setup.cfg
  src/ai/backend/gateway/auth.py
  src/ai/backend/gateway/config.py
  src/ai/backend/gateway/defs.py
  src/ai/backend/gateway/events.py
  src/ai/backend/gateway/exceptions.py
  src/ai/backend/gateway/kernel.py
  src/ai/backend/gateway/ratelimit.py
  src/ai/backend/gateway/resource.py
  src/ai/backend/gateway/server.py
  src/ai/backend/gateway/stream.py
  src/ai/backend/gateway/utils.py
  src/ai/backend/manager/models/agent.py
  src/ai/backend/manager/models/alembic/versions/405aa2c39458_job_queue.py
  src/ai/backend/manager/models/kernel.py
  src/ai/backend/manager/registry.py
  src/ai/backend/manager/scheduler.py
Labels: API, DB changes, blocker, enhancement

#193 Kernel creation error in non default sgroup
  src/ai/backend/gateway/exceptions.py
  src/ai/backend/manager/models/alembic/versions/9bd986a75a2a_allow_kernels_scaling_group_nullable.py
  src/ai/backend/manager/models/kernel.py
  src/ai/backend/manager/registry.py
  src/ai/backend/manager/scheduler.py
Labels: bug

#196 Sync user keypair role
  src/ai/backend/manager/models/user.py
Labels: minor

#197 Consistent logging format
  LOGGING.md
  src/ai/backend/gateway/admin.py
  src/ai/backend/gateway/auth.py
  src/ai/backend/gateway/etcd.py
  src/ai/backend/gateway/kernel.py
  src/ai/backend/gateway/manager.py
  src/ai/backend/gateway/resource.py
  src/ai/backend/gateway/scaling_group.py
  src/ai/backend/gateway/stream.py
  src/ai/backend/gateway/utils.py
  src/ai/backend/gateway/vfolder.py
  src/ai/backend/manager/scheduler.py
Labels: enhancement

#198 Refactor vfolder invitations
  src/ai/backend/gateway/auth.py
  src/ai/backend/gateway/vfolder.py
  src/ai/backend/manager/models/alembic/versions/6f5fe19894b7_vfolder_invitation_state_to_enum_type.py
  src/ai/backend/manager/models/vfolder.py
  tests/gateway/test_domain.py
  tests/gateway/test_vfolder.py
  tests/model_factory.py
Labels: DB changes, minor

#199 Support batch tasks
  src/ai/backend/gateway/kernel.py
  src/ai/backend/gateway/stream.py
  src/ai/backend/gateway/vfolder.py
  src/ai/backend/manager/models/alembic/versions/3f1dafab60b2_merge.py
  src/ai/backend/manager/models/alembic/versions/c092dabf3ee5_add_batch_session.py
  src/ai/backend/manager/models/kernel.py
  src/ai/backend/manager/registry.py
  src/ai/backend/manager/scheduler.py
Labels: API, DB changes, enhancement
