Repository lablup/backend.ai-manager, pull requests merged in 2020-07, with the labels that each got.

#290 feat: option to reserve batch session
  changes/290.feature
  src/ai/backend/gateway/session.py
  src/ai/backend/manager/models/alembic/versions/da24ff520049_add_starts_at_field_into_kernels.py
  src/ai/backend/manager/models/kernel.py
  src/ai/backend/manager/registry.py
  src/ai/backend/manager/scheduler/dispatcher.py
  src/ai/backend/manager/scheduler/predicates.py
  tests/manager/test_scheduler.py
Labels: bot:chronographer:provided, feature

#293 feat: add modified_at column to users and keypairs table
  changes/293.feature
  src/ai/backend/manager/models/alembic/versions/e35332f8d23d_add_modified_at_to_users_and_kernels.py
  src/ai/backend/manager/models/keypair.py
  src/ai/backend/manager/models/user.py
Labels: DB changes, bot:chronographer:provided, minor

#294 Add ability to change the schedulability of specific agents
  changes/294.feature
  src/ai/backend/gateway/manager.py
  src/ai/backend/manager/models/agent.py
  src/ai/backend/manager/models/alembic/versions/9cd61b1ae70d_add_scheduable_field_to_agents.py
  src/ai/backend/manager/scheduler/dispatcher.py
Labels: bot:chronographer:provided

#295 fix: Use of legacy API in "etcd move-subtree" manager command
  changes/295.fix
  src/ai/backend/manager/cli/etcd.py
Labels: bot:chronographer:provided

#296 fix: Mask sensitive keys when logging API params for debugging
  changes/296.fix
  src/ai/backend/gateway/utils.py
  tests/gateway/test_utils.py
Labels: bot:chronographer:provided

#298 Refactor session usage api
  changes/298.misc
  src/ai/backend/gateway/resource.py
Labels: bot:chronographer:provided, minor

#299 fix: convert user's uuid as str in key getter of fetching user by uuid
  changes/299.breaking
  changes/299.fix
  src/ai/backend/gateway/manager.py
  src/ai/backend/manager/models/gql.py
  src/ai/backend/manager/models/user.py
Labels: bot:chronographer:provided, bug

#300 fix: add context for the call to from_row in simple_db_mutate_returning_item
  changes/300.fix
  src/ai/backend/gateway/auth.py
  src/ai/backend/manager/models/base.py
  src/ai/backend/manager/models/resource_preset.py
Labels: bot:chronographer:provided, bug

#297 fix: raise explicit exception when no keypair is found during login
  changes/297.fix
  src/ai/backend/gateway/auth.py
Labels: bot:chronographer:provided, minor

#301 misc: return explicit message if user needs verification during login
  changes/301.misc
  src/ai/backend/gateway/auth.py
Labels: bot:chronographer:provided, minor

#303 fix: Return the session UUID after creating sessions
  changes/303.fix
  src/ai/backend/gateway/exceptions.py
  src/ai/backend/gateway/session.py
Labels: bot:chronographer:provided

#302 feat: add purge mutations for users, groups, and domains
  changes/302.feature
  src/ai/backend/manager/models/domain.py
  src/ai/backend/manager/models/gql.py
  src/ai/backend/manager/models/group.py
  src/ai/backend/manager/models/user.py
Labels: API, bot:chronographer:provided, feature

#307 fix(gateway.vfolder): parsing string params for bool/int
  changes/307.fix
  src/ai/backend/gateway/vfolder.py
Labels: bot:chronographer:provided
