Repository lablup/backend.ai-manager, pull requests merged in 2020-06, with the labels that each got.

#287 feat: pass Accept-Language header to post-signup hook
  changes/287.feature
  src/ai/backend/gateway/auth.py
Labels: bot:chronographer:provided, minor

#284 fix: Split db txns for starting sessions and scheduling computations
  changes/284.fix
  setup.cfg
  src/ai/backend/gateway/session.py
  src/ai/backend/manager/models/kernel.py
  src/ai/backend/manager/models/keypair.py
  src/ai/backend/manager/registry.py
  src/ai/backend/manager/scheduler/__init__.py
  src/ai/backend/manager/scheduler/dispatcher.py
  src/ai/backend/manager/scheduler/drf.py
  src/ai/backend/manager/scheduler/fifo.py
  src/ai/backend/manager/scheduler/mof.py
  src/ai/backend/manager/scheduler/predicates.py
Labels: bot:chronographer:provided

#288 feat: add a feature to kick off user who is shared virtual folder
  changes/288.feature
  src/ai/backend/gateway/vfolder.py
Labels: bot:chronographer:provided, feature, minor

#224 Implement per-user package directory feature
  changes/224.feature
  src/ai/backend/gateway/vfolder.py
  src/ai/backend/manager/registry.py
Labels: bot:chronographer:provided, feature

#289 Global announcement API
  changes/289.feature
  src/ai/backend/gateway/manager.py
Labels: bot:chronographer:provided

#278 Download a directory from vfolder as an archive
  changes/278.feature
  setup.cfg
  src/ai/backend/gateway/vfolder.py
Labels: bot:chronographer:provided, feature

#291 Refactor the plugins subsystem
  changes/291.breaking
  src/ai/backend/gateway/auth.py
  src/ai/backend/gateway/exceptions.py
  src/ai/backend/gateway/server.py
  src/ai/backend/gateway/session.py
  src/ai/backend/gateway/types.py
  src/ai/backend/manager/plugin/__init__.py
  src/ai/backend/manager/plugin/exceptions.py
  src/ai/backend/manager/plugin/webapp.py
  src/ai/backend/manager/registry.py
  tests/conftest.py
  tests/gateway/test_auth.py
  tests/gateway/test_events.py
  tests/gateway/test_ratelimit.py
  tests/manager/test_registry.py
Labels: bot:chronographer:provided

#292 fix: Ensure kernel IDs for registry operations
  changes/292.fix
  src/ai/backend/manager/registry.py
Labels: bot:chronographer:provided, bug
