Repository lablup/backend.ai-manager, pull requests merged in 2020-12, with the labels that each got.

#357 Rewrite container registry support
  changes/357.feature
  src/ai/backend/gateway/config.py
  src/ai/backend/manager/cli/__main__.py
  src/ai/backend/manager/cli/etcd.py
  src/ai/backend/manager/container_registry/__init__.py
  src/ai/backend/manager/container_registry/base.py
  src/ai/backend/manager/container_registry/docker.py
  src/ai/backend/manager/container_registry/harbor.py
  tests/conftest.py
Labels: blocker, bot:chronographer:provided, feature

#358 fix: Update and clean up fixtures
  changes/358.fix
  fixtures/example-keypairs.json
  fixtures/example-resource-presets.json
  sample-configs/image-aliases.yml
  sample-configs/image-metadata.yml
  sample-configs/volumes-local.yml
  sample-configs/volumes.yml
Labels: bot:chronographer:provided, feature

#359 setup: Update dependencies
  changes/359.misc
  setup.cfg
Labels: bot:chronographer:provided, feature

#362 setup: Update aiotools to fix a potential memory leak with long-lived taskgroups
  changes/362.fix
  setup.cfg
Labels: bot:chronographer:provided, bug

#364 ci: Migrate to GitHub Actions completely
  .github/workflows/default.yml
  .github/workflows/lint-flake8.yml
  .github/workflows/timeline-check.yml
  .github/workflows/typecheck-mypy.yml
  .travis.yml
  changes/364.misc
  requirements/build.txt
  scripts/set-psql-superuser.sql
Labels: feature

#360 fix: exception on handling broken symlinks in file list API
  changes/360.fix
  src/ai/backend/gateway/vfolder.py
Labels: bug

#365 fix: Improve shutdown with live sessions
  changes/365.fix
  src/ai/backend/gateway/ratelimit.py
  src/ai/backend/gateway/stream.py
Labels: bug

#368 fix: A race condition that corrupts the kernel status during kernel creation
  changes/368.fix
  src/ai/backend/manager/registry.py
Labels: bug

#363 feat: support destroying PREPARING/TERMINATING/ERROR sessions when forced
  changes/363.feature
  src/ai/backend/gateway/session.py
  src/ai/backend/manager/registry.py
Labels: feature, minor

#361 fix: unable to purge user and group in 20.09
  changes/361.fix
  src/ai/backend/gateway/admin.py
  src/ai/backend/manager/models/group.py
  src/ai/backend/manager/models/user.py
Labels: bug

#369 fix: Race condition of kernel status update during kernel creation
  changes/369.fix
  src/ai/backend/manager/registry.py
Labels: bug

#366 Support for hardware metadata queries
  changes/366.feature
  src/ai/backend/gateway/admin.py
  src/ai/backend/gateway/manager.py
  src/ai/backend/manager/models/__init__.py
  src/ai/backend/manager/models/agent.py
  src/ai/backend/manager/models/gql.py
  src/ai/backend/manager/models/storage.py
  src/ai/backend/manager/registry.py
Labels: API, feature

#372 Improve multi-node multi-container scheduling
  changes/372.fix
  scripts/query-test.py
  setup.cfg
  src/ai/backend/gateway/events.py
  src/ai/backend/gateway/exceptions.py
  src/ai/backend/gateway/session.py
  src/ai/backend/manager/exceptions.py
  src/ai/backend/manager/models/alembic/versions/250e8656cf45_add_status_data.py
  src/ai/backend/manager/models/kernel.py
  src/ai/backend/manager/models/utils.py
  src/ai/backend/manager/registry.py
  src/ai/backend/manager/scheduler/dispatcher.py
Labels: feature

#374 Fix races of kernel creation events
  changes/374.fix
  src/ai/backend/gateway/session.py
  src/ai/backend/manager/registry.py
Labels: blocker, bug

#373 Multi-node multi-container stabilization
  changes/373.fix
  scripts/query-test.py
  setup.cfg
  src/ai/backend/gateway/events.py
  src/ai/backend/gateway/session.py
  src/ai/backend/manager/models/agent.py
  src/ai/backend/manager/models/alembic/versions/06184d82a211_add_session_creation_id.py
  src/ai/backend/manager/models/alembic/versions/dc9b66466e43_remove_clusterized.py
  src/ai/backend/manager/models/kernel.py
  src/ai/backend/manager/models/utils.py
  src/ai/backend/manager/registry.py
  src/ai/backend/manager/scheduler/__init__.py
  src/ai/backend/manager/scheduler/dispatcher.py
  src/ai/backend/manager/scheduler/predicates.py
  tests/manager/test_registry.py
  tests/manager/test_scheduler.py
Labels: feature

#376 Stabilization of multi-node multi-container sessions (Phase 3)
  changes/376.fix
  src/ai/backend/manager/exceptions.py
  src/ai/backend/manager/registry.py
  src/ai/backend/manager/scheduler/__init__.py
  src/ai/backend/manager/scheduler/dispatcher.py
  src/ai/backend/manager/scheduler/predicates.py
Labels: feature

#378 fix: Remove use of deprecated asyncio API
  changes/378.fix
  src/ai/backend/gateway/session.py
  src/ai/backend/gateway/stream.py
Labels: bug

#379 fix: Duplicate entries in passed/failed predicates
  changes/379.fix
  src/ai/backend/manager/scheduler/dispatcher.py
Labels: bug

#380 fix: A missing kernel ID field during cancel-termination of a session
  changes/380.fix
  src/ai/backend/manager/scheduler/dispatcher.py
Labels: bug
