Repository lablup/backend.ai-manager, pull requests merged in 2020-04, with the labels that each got.

#259 fix: error on fetching docker registry list
  src/ai/backend/gateway/etcd.py
Labels: bug

#261 fix: use get_allowed_vfolder_hosts_by_user when creating user folder
  src/ai/backend/gateway/vfolder.py
Labels: bug

#262 feat: Adopt towncrier and migrate changelog for the next release
  CHANGELOG.md
  HISTORY.rst
  changes/0.breaking
  changes/0.feature
  changes/0.misc
  changes/209.feature
  changes/210.feature
  changes/212.feature
  changes/213.feature
  changes/214.feature
  changes/216.breaking
  changes/221.feature
  changes/234.feature
  changes/235.feature
  changes/236.feature
  changes/241.feature
  changes/253.feature
  changes/258.feature
  changes/259.fix
  changes/262.misc
  changes/template.md
  pyproject.toml
  setup.cfg
Labels: bot:chronographer:provided

#264 fix: error fetching server error logs
  changes/264.fix
  src/ai/backend/gateway/logs.py
  src/ai/backend/manager/models/vfolder.py
Labels: bot:chronographer:provided, bug

#266 feat: API to rename file inside a virtual folder
  changes/266.feature
  src/ai/backend/gateway/vfolder.py
Labels: API, bot:chronographer:provided, feature

#267 Add shared memory column to resource preset
  changes/267.feature
  src/ai/backend/gateway/resource.py
  src/ai/backend/manager/models/alembic/versions/c481d3dc6c7d_add_shared_memory_to_resource_presets.py
  src/ai/backend/manager/models/resource_preset.py
Labels: DB changes, bot:chronographer:provided, feature, minor

#268 refactor: return NaN if group-level resource status is not allowed
  changes/268.misc
  src/ai/backend/gateway/etcd.py
  src/ai/backend/gateway/resource.py
Labels: bot:chronographer:provided, minor

#271 feat: Adopt towncrier for changelog mgmt
  CHANGELOG.md
  HISTORY.md
  changes/271.misc
  changes/template.md
  pyproject.toml
  setup.cfg
Labels: bot:chronographer:provided

#270 fix: Prevent destroying kernels in PREPARING/PULLING status
  changes/270.fix
  src/ai/backend/manager/registry.py
Labels: bot:chronographer:provided

#273 backport: shared memory to resource preset
  changes/267.feature
  src/ai/backend/gateway/resource.py
  src/ai/backend/manager/models/alembic/versions/c481d3dc6c7d_add_shared_memory_to_resource_presets.py
  src/ai/backend/manager/models/resource_preset.py
Labels: DB changes, bot:chronographer:provided, feature, minor

#265 feat: extend vfolder to have innate permission and usage mode
  changes/265.feature
  sample-configs/example-resource-presets.json
  src/ai/backend/gateway/vfolder.py
  src/ai/backend/manager/models/alembic/versions/529113b08c2c_add_vfolder_type_column.py
  src/ai/backend/manager/models/vfolder.py
Labels: DB changes, bot:chronographer:provided, feature

#274 fix: Missing concurrency update for self-terminated sessions
  changes/274.fix
  src/ai/backend/manager/registry.py
Labels: bot:chronographer:provided
