Repository lablup/backend.ai-manager, pull requests merged in 2020-10, with the labels that each got.

#323 Support vfolder clone
  changes/323.feature
  src/ai/backend/gateway/vfolder.py
  src/ai/backend/manager/models/alembic/versions/d463fc5d6109_add_clone_allowed_to_vfolders.py
  src/ai/backend/manager/models/alembic/versions/eec98e65902a_merge_with_vfolder_clone.py
  src/ai/backend/manager/models/vfolder.py
Labels: bot:chronographer:provided, feature

#325 Support backend for xfs
  changes/325.feature
  src/ai/backend/gateway/vfolder.py
Labels: bot:chronographer:provided, feature

#338 fix: Follow-up fixes for #323
  changes/338.fix
  src/ai/backend/gateway/vfolder.py
  src/ai/backend/manager/models/alembic/versions/57e717103287_rename_clone_allowed_to_clonable.py
  src/ai/backend/manager/models/vfolder.py
Labels: bot:chronographer:provided

#336 feat: make vfolder's mkdir to accept and deliver parents and exist_ok option
  changes/336.feature
  src/ai/backend/gateway/vfolder.py
Labels: bot:chronographer:provided, feature, minor

#337 fix: get_task_logs references deprecated etcd config
  changes/337.feature
  src/ai/backend/gateway/exceptions.py
  src/ai/backend/gateway/session.py
Labels: bot:chronographer:provided, bug

#339 feat: add hooking point for AUTHORIZE
  changes/339.feature
  src/ai/backend/gateway/auth.py
Labels: bot:chronographer:provided

#340 fix: unable to invite user to a vfolder, which is shared with another user
  changes/340.fix
  src/ai/backend/gateway/auth.py
  src/ai/backend/gateway/vfolder.py
Labels: bot:chronographer:provided, bug

#343 Fix regression in vfolder APIs
  .travis.yml
  changes/343.fix
  setup.cfg
  src/ai/backend/gateway/vfolder.py
  src/ai/backend/manager/models/base.py
  src/ai/backend/manager/models/gql.py
  src/ai/backend/manager/models/vfolder.py
Labels: bot:chronographer:provided, bug

#344 fix: Ensure removal of vfolders in db when storage-proxy returns error
  changes/344.fix
  src/ai/backend/gateway/vfolder.py
Labels: bot:chronographer:provided, bug

#342 fix: read manager ID from keys of etcd_info
  changes/342.fix
  src/ai/backend/gateway/manager.py
Labels: bot:chronographer:provided, bug

#345 fix: update dependencies (aiohttp~=3.7.0, trafaret~=2.1)
  changes/345.fix
  setup.cfg
Labels: bot:chronographer:provided

#327 Feature/shutdown service apps
  changes/327.feature
  src/ai/backend/gateway/session.py
  src/ai/backend/gateway/utils.py
  src/ai/backend/manager/registry.py
Labels: bot:chronographer:provided, feature
