Repository lablup/backend.ai-manager, pull requests merged in 2020-01, with the labels that each got.

#215 Refactoring for better unit tests
  codecov.yml
  setup.cfg
  src/ai/backend/gateway/etcd.py
  src/ai/backend/gateway/events.py
  src/ai/backend/gateway/manager.py
  src/ai/backend/gateway/server.py
  src/ai/backend/gateway/typing.py
  src/ai/backend/manager/cli/etcd.py
  src/ai/backend/manager/models/base.py
  src/ai/backend/manager/models/kernel.py
  tests/conftest.py
  tests/gateway/test_auth.py
  tests/gateway/test_events.py
  tests/gateway/test_ratelimit.py
  tests/manager/test_registry.py
Labels: enhancement

#209 Adopt Callosum
  .travis.yml
  CHANGELOG.rst
  DEPENDENCIES.md
  PY38.md
  setup.cfg
  src/ai/backend/gateway/exceptions.py
  src/ai/backend/manager/registry.py
Labels: enhancement

#219 Make all vfolder operations to be async
  setup.cfg
  src/ai/backend/gateway/config.py
  src/ai/backend/gateway/vfolder.py
Labels: bug

#222 Append agent ids when fetching image list
  src/ai/backend/gateway/etcd.py
  src/ai/backend/manager/models/image.py
Labels: minor
