Repository lablup/backend.ai-manager, pull requests merged in 2020-11, with the labels that each got.

#346 fix: Regression of container logs after session ID/name match refactoring
  changes/346.fix
  src/ai/backend/gateway/session.py
  src/ai/backend/manager/models/kernel.py
  src/ai/backend/manager/registry.py
Labels: bot:chronographer:provided, bug

#347 fix: Regression of per-session app starting
  changes/347.fix
  src/ai/backend/gateway/stream.py
  src/ai/backend/gateway/wsproxy.py
Labels: blocker, bot:chronographer:provided, bug

#349 fix: Replace all fetchone() with first() or scalar()
  changes/349.fix
  src/ai/backend/gateway/auth.py
  src/ai/backend/gateway/cluster_template.py
  src/ai/backend/gateway/image.py
  src/ai/backend/gateway/resource.py
  src/ai/backend/gateway/session.py
  src/ai/backend/gateway/session_template.py
  src/ai/backend/gateway/utils.py
  src/ai/backend/manager/models/agent.py
  src/ai/backend/manager/models/alembic/versions/819c2b3830a9_add_user_model.py
  src/ai/backend/manager/models/alembic/versions/bae1a7326e8a_add_domain_model.py
  src/ai/backend/manager/models/alembic/versions/c5e4e764f9e3_add_domain_group_user_fields_to_kernels.py
  src/ai/backend/manager/models/alembic/versions/e18ed5fcfedf_add_superadmin_role_for_user.py
  src/ai/backend/manager/models/image.py
  src/ai/backend/manager/models/kernel.py
  src/ai/backend/manager/models/keypair.py
  src/ai/backend/manager/models/resource_policy.py
  src/ai/backend/manager/models/user.py
  src/ai/backend/manager/models/vfolder.py
  src/ai/backend/manager/registry.py
  tests/model_factory.py
Labels: bot:chronographer:provided, bug

#348 fix: replace legacy sess_id to session_name
  changes/348.fix
  src/ai/backend/gateway/resource.py
  src/ai/backend/gateway/session.py
Labels: bot:chronographer:provided, bug

#341 Rewriting idle checks
  .github/workflows/lint-flake8.yml
  .github/workflows/typecheck-mypy.yml
  changes/341.feature
  changes/341.fix
  setup.cfg
  src/ai/backend/gateway/admin.py
  src/ai/backend/gateway/config.py
  src/ai/backend/gateway/etcd.py
  src/ai/backend/gateway/events.py
  src/ai/backend/gateway/image.py
  src/ai/backend/gateway/logs.py
  src/ai/backend/gateway/manager.py
  src/ai/backend/gateway/ratelimit.py
  src/ai/backend/gateway/resource.py
  src/ai/backend/gateway/server.py
  src/ai/backend/gateway/session.py
  src/ai/backend/gateway/stream.py
  src/ai/backend/gateway/vfolder.py
  src/ai/backend/manager/cli/etcd.py
  src/ai/backend/manager/defs.py
  src/ai/backend/manager/distributed.py
  src/ai/backend/manager/idle.py
  src/ai/backend/manager/models/base.py
  src/ai/backend/manager/models/domain.py
  src/ai/backend/manager/models/group.py
  src/ai/backend/manager/models/keypair.py
  src/ai/backend/manager/models/vfolder.py
  src/ai/backend/manager/registry.py
  src/ai/backend/manager/scheduler/__init__.py
  src/ai/backend/manager/scheduler/dispatcher.py
  tests/conftest.py
  tests/gateway/test_auth.py
  tests/gateway/test_config.py
  tests/gateway/test_etcd.py
  tests/gateway/test_events.py
  tests/gateway/test_ratelimit.py
  tests/manager/test_distributed.py
  tests/manager/test_registry.py
Labels: blocker, bot:chronographer:provided, feature

#350 fix: update compute_plugins info from heartbeat for an ALIVE agent
  changes/350.fix
  src/ai/backend/manager/registry.py
Labels: bot:chronographer:provided, bug, minor

#353 fix: unable to signout
  changes/353.fix
  src/ai/backend/gateway/auth.py
Labels: bot:chronographer:provided, bug

#354 fix: replace config_server legacy code to shared_config
  changes/354.fix
  src/ai/backend/gateway/etcd.py
  src/ai/backend/gateway/resource.py
  src/ai/backend/gateway/vfolder.py
  src/ai/backend/manager/models/group.py
  src/ai/backend/manager/models/image.py
  src/ai/backend/manager/models/user.py
Labels: bot:chronographer:provided, bug, minor

#352 fix: wrap storage manager request with try-exception block
  changes/352.fix
  src/ai/backend/gateway/exceptions.py
  src/ai/backend/gateway/vfolder.py
Labels: bot:chronographer:provided

#355 fix: Regression of fetching live_stat GQL fields
  changes/355.fix
  src/ai/backend/manager/models/kernel.py
Labels: bot:chronographer:provided, bug

#356 fix: Improve error message for image not found errors
  changes/356.fix
  src/ai/backend/gateway/session.py
Labels: API, bot:chronographer:provided, minor
