Repository lablup/backend.ai-manager, pull requests merged in 2020-05, with the labels that each got.

#275 fix: remove unwanted nested dict empty key("")
  changes/275.fix
  src/ai/backend/gateway/etcd.py
Labels: bot:chronographer:provided, bug, minor

#276 fix: set correct scaling group name during session scheduling
  changes/276.fix
  src/ai/backend/manager/scheduler.py
Labels: bot:chronographer:provided

#277 ci: Update flake8 to a prerelease version supporting Python 3.8 syntaxes
  changes/277.misc
  requirements/dev.txt
  requirements/lint.txt
  setup.cfg
Labels: bot:chronographer:provided

#263 Migrate to APIv5
  .editorconfig
  changes/263.breaking
  changes/263.feature
  changes/263.misc
  setup.cfg
  src/ai/backend/gateway/admin.py
  src/ai/backend/gateway/auth.py
  src/ai/backend/gateway/etcd.py
  src/ai/backend/gateway/events.py
  src/ai/backend/gateway/image.py
  src/ai/backend/gateway/logs.py
  src/ai/backend/gateway/manager.py
  src/ai/backend/gateway/ratelimit.py
  src/ai/backend/gateway/resource.py
  src/ai/backend/gateway/scaling_group.py
  src/ai/backend/gateway/server.py
  src/ai/backend/gateway/session.py
  src/ai/backend/gateway/session_template.py
  src/ai/backend/gateway/stream.py
  src/ai/backend/gateway/types.py
  src/ai/backend/gateway/userconfig.py
  src/ai/backend/manager/background.py
  src/ai/backend/manager/cli/__main__.py
  src/ai/backend/manager/cli/dbschema.py
  src/ai/backend/manager/cli/etcd.py
  src/ai/backend/manager/cli/fixture.py
  src/ai/backend/manager/cli/gql.py
  src/ai/backend/manager/models/agent.py
  src/ai/backend/manager/models/base.py
  src/ai/backend/manager/models/domain.py
  src/ai/backend/manager/models/gql.py
  src/ai/backend/manager/models/group.py
  src/ai/backend/manager/models/image.py
  src/ai/backend/manager/models/kernel.py
  src/ai/backend/manager/models/keypair.py
  src/ai/backend/manager/models/resource_policy.py
  src/ai/backend/manager/models/resource_preset.py
  src/ai/backend/manager/models/scaling_group.py
  src/ai/backend/manager/models/user.py
  src/ai/backend/manager/models/vfolder.py
  src/ai/backend/manager/types.py
  tests/conftest.py
  tests/gateway/test_events.py
Labels: bot:chronographer:provided

#279 fix: Return the last-stat from Redis when destroying sessions
  changes/279.fix
  src/ai/backend/gateway/config.py
  src/ai/backend/gateway/utils.py
  src/ai/backend/gateway/vfolder.py
  src/ai/backend/manager/models/vfolder.py
  src/ai/backend/manager/registry.py
  tests/gateway/test_etcd.py
  tests/gateway/test_vfolder.py
Labels: bot:chronographer:provided

#280 fix: Apply batching to stat sync
  changes/280.fix
  src/ai/backend/gateway/kernel.py
  src/ai/backend/manager/registry.py
Labels: bot:chronographer:provided

#281 fix: Split and serialize DB txns for session starts in the scheduler
  changes/281.fix
  src/ai/backend/manager/scheduler.py
Labels: bot:chronographer:provided

#282 fix: add fallback if any keys under last_stat have None value
  changes/282.fix
  src/ai/backend/gateway/resource.py
Labels: bot:chronographer:provided, bug, minor

#283 fix: Response for compute_session GQL query
  changes/283.fix
  src/ai/backend/gateway/exceptions.py
  src/ai/backend/manager/models/gql.py
  src/ai/backend/manager/models/kernel.py
Labels: bot:chronographer:provided

#285 fix: Further split DB txns in scheduler
  changes/285.fix
  setup.cfg
  src/ai/backend/manager/models/kernel.py
  src/ai/backend/manager/models/keypair.py
  src/ai/backend/manager/registry.py
  src/ai/backend/manager/scheduler.py
Labels: bot:chronographer:provided

#286 feat: execute POST_SIGNUP hook after sign up
  changes/286.feature
  src/ai/backend/gateway/auth.py
  src/ai/backend/gateway/exceptions.py
  src/ai/backend/gateway/server.py
  src/ai/backend/manager/plugin/__init__.py
  tests/conftest.py
  tests/gateway/test_auth.py
  tests/gateway/test_events.py
  tests/gateway/test_ratelimit.py
Labels: bot:chronographer:provided, feature
