Repository lablup/backend.ai-manager, pull requests merged in 2020-03, with the labels that each got.

#232 Collect container logs at container termination
  .github/workflows/typecheck-mypy.yml
  src/ai/backend/gateway/session.py
  src/ai/backend/manager/models/alembic/versions/51dddd79aa21_add_logs_column_on_kernel_table.py
  src/ai/backend/manager/models/kernel.py
  tests/conftest.py
Labels: feature

#250 Support for forced termination of sessions
  CHANGELOG.rst
  src/ai/backend/gateway/kernel.py
  src/ai/backend/gateway/resource.py
  src/ai/backend/manager/registry.py
Labels: API, feature

#252 Support pagination for rescan-images
  src/ai/backend/gateway/admin.py
  src/ai/backend/gateway/etcd.py
Labels: bug

#255 Add missing ForgetImage GQL mutation
  src/ai/backend/manager/models/gql.py
  src/ai/backend/manager/models/image.py
Labels: feature

#254 Add missing GQL mutation privilege checks
  src/ai/backend/gateway/admin.py
  src/ai/backend/gateway/exceptions.py
  src/ai/backend/gateway/kernel.py
  src/ai/backend/manager/models/base.py
  src/ai/backend/manager/models/domain.py
  src/ai/backend/manager/models/gql.py
  src/ai/backend/manager/models/group.py
  src/ai/backend/manager/models/image.py
  src/ai/backend/manager/models/keypair.py
  src/ai/backend/manager/models/resource_policy.py
  src/ai/backend/manager/models/resource_preset.py
  src/ai/backend/manager/models/scaling_group.py
  src/ai/backend/manager/models/user.py
Labels: bug

#249 Improve scheduling ticks using Redis as the central clock
  src/ai/backend/gateway/ratelimit.py
  src/ai/backend/manager/scheduler/dispatcher.py
Labels: feature

#253 Add API to update/get keypair bootstrap script
  src/ai/backend/gateway/session.py
  src/ai/backend/gateway/userconfig.py
  src/ai/backend/manager/models/alembic/versions/ed666f476f39_add_bootstrap_script_to_keypairs.py
  src/ai/backend/manager/models/keypair.py
  src/ai/backend/manager/registry.py
Labels: API, DB changes, feature

#230 Implement background task
  src/ai/backend/gateway/server.py
  src/ai/backend/gateway/stream.py
  src/ai/backend/manager/background.py
  tests/gateway/test_events.py
Labels: feature

#256 Fix wrong parameter check routine for trafaret
  src/ai/backend/gateway/session.py
Labels: bug
