Repository lablup/backend.ai-manager, pull requests merged in 2020-08, with the labels that each got.

#308 fix: do not create invitation if target user is already shared the folder
  changes/308.fix
  src/ai/backend/gateway/vfolder.py
Labels: minor

#306 fix: prevent purging a user, group, and domain if bound resources are being used
  changes/306.fix
  src/ai/backend/manager/models/domain.py
  src/ai/backend/manager/models/group.py
  src/ai/backend/manager/models/user.py
Labels: bot:chronographer:provided, bug, minor

#311 fix: regression of single-session GQL query
  changes/311.fix
  src/ai/backend/manager/models/gql.py
Labels: bot:chronographer:provided

#312 Storage Proxy
  changes/0.breaking
  changes/312.breaking
  changes/312.feature
  config/sample.volume.json
  src/ai/backend/gateway/config.py
  src/ai/backend/gateway/etcd.py
  src/ai/backend/gateway/server.py
  src/ai/backend/gateway/vfolder.py
  src/ai/backend/manager/exceptions.py
  src/ai/backend/manager/models/storage.py
Labels: bot:chronographer:provided

#313 feat: include user information in keypair gql query
  changes/313.feature
  src/ai/backend/manager/models/keypair.py
Labels: API, bot:chronographer:provided, minor

#314 fix: return shared memory in preset list API
  changes/314.fix
  src/ai/backend/gateway/resource.py
Labels: bot:chronographer:provided, minor

#315 fix: wrong column names in server-side error-logs query API
  changes/315.fix
  src/ai/backend/gateway/logs.py
Labels: bot:chronographer:provided

#316 fix: regression of error logs API
  changes/316.fix
  setup.cfg
  src/ai/backend/gateway/logs.py
  src/ai/backend/gateway/server.py
  src/ai/backend/manager/plugin/error_monitor.py
Labels: bot:chronographer:provided

#305 Add a mini-language parser for generic GQL list filtering
  changes/305.feature
  setup.cfg
  src/ai/backend/manager/models/minilang/__init__.py
  src/ai/backend/manager/models/minilang/queryfilter.py
  tests/manager/test_queryfilter.py
Labels: bot:chronographer:provided, feature

#318 Smarter dbshell command
  changes/318.feature
  src/ai/backend/manager/cli/__main__.py
Labels: bot:chronographer:provided
