Repository lablup/backend.ai-manager, pull requests merged in 2020-02, with the labels that each got.

#227 Add get/update API for bootstrap script
  src/ai/backend/gateway/userconfig.py
  src/ai/backend/manager/models/alembic/versions/4808cdea8592_add_bootstrap_script_column_to_keypairs.py
  src/ai/backend/manager/models/keypair.py
  src/ai/backend/manager/registry.py
Labels: API, DB changes

#233 Fix a bogus error due to missing livestat while agents starting up
  codecov.yml
  src/ai/backend/manager/models/agent.py
Labels: bug

#234 Auto-fill the minimum resource slots for intrinsic slots only
  src/ai/backend/gateway/defs.py
  src/ai/backend/gateway/etcd.py
  src/ai/backend/manager/defs.py
  src/ai/backend/manager/registry.py
Labels: bug

#236 Improve scheduling ticks
  src/ai/backend/gateway/etcd.py
  src/ai/backend/gateway/server.py
  src/ai/backend/manager/scheduler/dispatcher.py
Labels: feature

#221 Pre-open service ports
  src/ai/backend/gateway/session.py
  src/ai/backend/gateway/stream.py
  src/ai/backend/manager/models/alembic/versions/3bb80d1887d6_add_preopen_ports.py
  src/ai/backend/manager/models/kernel.py
  src/ai/backend/manager/registry.py
  src/ai/backend/manager/scheduler/__init__.py
  src/ai/backend/manager/scheduler/dispatcher.py
  tests/manager/test_scheduler.py
Labels: feature

#241 Favor CPU agents for session creation requests without accelerators
  src/ai/backend/manager/scheduler/fifo.py
  tests/manager/test_scheduler.py
Labels: feature

#242 Backport: Favor CPU agents for session request without accelerators
  src/ai/backend/manager/scheduler.py
Labels: feature

#243 Fix potential memory leak in stream APIs
  setup.cfg
  src/ai/backend/gateway/stream.py
Labels: bug
