Repository lablup/backend.ai-manager, pull requests merged in 2020-09, with the labels that each got.

#320 feat: Make the maximum websocket message size configurable
  changes/320.feature
  src/ai/backend/gateway/config.py
  src/ai/backend/gateway/stream.py
Labels: bot:chronographer:provided

#322 fix: Deduplicate explicitly raised internal server errors
  changes/322.fix
  src/ai/backend/gateway/server.py
Labels: bot:chronographer:provided

#319 script migrate vfolder structure
  changes/319.feature
  scripts/migrate-vfolder-structure.py
Labels: bot:chronographer:provided

#317 Feature: Add functionality for the user to leave a shared vfolder
  changes/317.feature
  src/ai/backend/gateway/vfolder.py
Labels: bot:chronographer:provided

#326 fix: regression of statistics API due to wrong default value type
  changes/326.fix
  src/ai/backend/gateway/resource.py
Labels: bot:chronographer:provided

#328 fix: Use the storage-proxy provided mount path for vfolders
  changes/328.fix
  src/ai/backend/gateway/server.py
  src/ai/backend/gateway/vfolder.py
  src/ai/backend/manager/models/storage.py
  src/ai/backend/manager/registry.py
Labels: bot:chronographer:provided

#334 fix: Improve pickling of gateway exceptions
  changes/334.fix
  src/ai/backend/gateway/exceptions.py
  src/ai/backend/gateway/server.py
  src/ai/backend/gateway/session.py
  tests/manager/test_registry.py
Labels: bot:chronographer:provided

#330 fix: hand over recursive parameter to storage proxy when delete_files
  changes/330.fix
  src/ai/backend/gateway/vfolder.py
Labels: bot:chronographer:provided, bug, minor

#324 fix: log detailed error messages when there are graphQl exceptions
  changes/324.fix
  src/ai/backend/gateway/admin.py
Labels: bot:chronographer:provided, minor

#335 fix: Show the container name when using "mgr dbshell" cli command
  changes/335.fix
  src/ai/backend/manager/cli/__main__.py
Labels: bot:chronographer:provided

#329 Add support for dotfiles of domains and groups
  changes/329.feature
  src/ai/backend/gateway/domainconfig.py
  src/ai/backend/gateway/exceptions.py
  src/ai/backend/gateway/groupconfig.py
  src/ai/backend/gateway/server.py
  src/ai/backend/gateway/vfolder.py
  src/ai/backend/manager/models/alembic/versions/25e903510fa1_add_dotfiles_to_domains_and_groups.py
  src/ai/backend/manager/models/domain.py
  src/ai/backend/manager/models/group.py
  src/ai/backend/manager/registry.py
Labels: API, DB changes, bot:chronographer:provided, feature

#333 Validate service ports before starting session
  changes/333.fix
  src/ai/backend/manager/registry.py
Labels: bot:chronographer:provided
