Repository lablup/backend.ai-manager, pull requests merged in 2021-09, with the labels that each got.

#476 fix: Regression of Agent.batch_load due to arg name changes
  changes/476.fix
  src/ai/backend/manager/models/agent.py
  src/ai/backend/manager/models/gql.py
Labels: bug

#473 refactor: re-arrange the order of alias folder name checking codes
  changes/473.fix
  src/ai/backend/manager/api/session.py
Labels: enhancement, minor

#474 feature: provide extra operations for storage proxy
  changes/474.feature
  src/ai/backend/manager/api/vfolder.py
Labels: enhancement, help wanted, blocker, API
