Repository lablup/backend.ai-manager, pull requests merged in 2021-10, with the labels that each got.

#481 fix: more realistic resource preset fixtures
  changes/481.fix
  fixtures/example-resource-presets.json
Labels: minor

#482 fix: Replace aioredlock with pg_advisory_lock
  changes/482.fix
  setup.cfg
  src/ai/backend/manager/api/logs.py
  src/ai/backend/manager/defs.py
  src/ai/backend/manager/distributed.py
  src/ai/backend/manager/idle.py
  src/ai/backend/manager/models/utils.py
  src/ai/backend/manager/scheduler/dispatcher.py
  tests/conftest.py
  tests/test_advisory_lock.py
  tests/test_distributed.py
Labels: bug, enhancement

#483 fix: Improve advisory locks (follow-up to #482)
  changes/483.fix
  src/ai/backend/manager/models/utils.py
  src/ai/backend/manager/server.py
  tests/api/test_auth.py
  tests/conftest.py
  tests/test_advisory_lock.py
  tests/test_distributed.py
Labels: bug

#484 fix: Apply TCP keepalive settings to ZeroMQ sockets for RPC channels
  changes/484.fix
  setup.cfg
  src/ai/backend/manager/registry.py
Labels: enhancement

#485 feat: Allow config of RPC keepalive timeout via etcd
  changes/485.feature
  src/ai/backend/manager/config.py
  src/ai/backend/manager/registry.py
Labels: enhancement

#486 Fix: Ignore malformed image when listing available images
  changes/486.fix
  src/ai/backend/manager/config.py
Labels: bug

#487 fix: unable to get response from usage per period API
  changes/487.fix
  src/ai/backend/manager/api/resource.py
Labels: bug

#478 Upgrade to aioredis v2
  .github/workflows/default.yml
  .gitignore
  changes/478.feature
  config/sample.etcd.redis-sentinel.json
  config/sample.etcd.redis-single.json
  scripts/switch-redis.sh
  setup.cfg
  src/ai/backend/manager/api/auth.py
  src/ai/backend/manager/api/context.py
  src/ai/backend/manager/api/events.py
  src/ai/backend/manager/api/logs.py
  src/ai/backend/manager/api/ratelimit.py
  src/ai/backend/manager/api/session.py
  src/ai/backend/manager/api/stream.py
  src/ai/backend/manager/background.py
  src/ai/backend/manager/config.py
  src/ai/backend/manager/idle.py
  src/ai/backend/manager/models/agent.py
  src/ai/backend/manager/models/gql.py
  src/ai/backend/manager/models/image.py
  src/ai/backend/manager/models/kernel.py
  src/ai/backend/manager/models/keypair.py
  src/ai/backend/manager/registry.py
  src/ai/backend/manager/scheduler/dispatcher.py
  src/ai/backend/manager/server.py
  tests/api/test_events.py
  tests/test_distributed.py
  tests/test_registry.py
Labels: enhancement
