Repository lablup/backend.ai-manager, pull requests merged in 2021-11, with the labels that each got.

#492 feat: allow users to query/update their vfolder quota
  changes/492.feature
  src/ai/backend/manager/api/vfolder.py
Labels: blocker, API, minor, feature

#491 feat: return version information in status API
  changes/491.feature
  src/ai/backend/manager/api/manager.py
Labels: enhancement, minor

#494 feat: add usage API for vfolder (superadmin only)
  changes/494.feature
  src/ai/backend/manager/api/vfolder.py
Labels: enhancement, API

#469 feat: Add optional manually-assigned agent list to session creation API
  changes/469.feature
  src/ai/backend/manager/api/session.py
  src/ai/backend/manager/registry.py
  src/ai/backend/manager/scheduler/dispatcher.py
  src/ai/backend/manager/scheduler/types.py
  tests/test_scheduler.py
Labels: feature

#495 fix: Improve session/kernel event notification stability
  changes/495.fix
  src/ai/backend/manager/api/events.py
  src/ai/backend/manager/models/keypair.py
Labels: bug

#496 setup: Upgrade aiohttp to 3.8
  changes/496.fix
  setup.cfg
  src/ai/backend/manager/api/admin.py
  src/ai/backend/manager/api/auth.py
  src/ai/backend/manager/api/etcd.py
  src/ai/backend/manager/api/manager.py
  src/ai/backend/manager/api/resource.py
  src/ai/backend/manager/api/session.py
  src/ai/backend/manager/api/vfolder.py
  src/ai/backend/manager/background.py
  src/ai/backend/manager/server.py
Labels: enhancement

#480 feat: Update CRUD of session template.
  changes/480.feature
  fixtures/example-session-templates.json
  src/ai/backend/manager/api/session.py
  src/ai/backend/manager/api/session_template.py
  src/ai/backend/manager/models/session_template.py
Labels: bug, feature

#497 fix: Remove reusable caching for RPC peer objects
  changes/497.fix
  src/ai/backend/manager/registry.py
Labels: bug
