Repository lablup/backend.ai-manager, pull requests merged in 2021-07, with the labels that each got.

#444 fix: Handle failure of advisory locks gracefully
  changes/444.fix
  src/ai/backend/manager/scheduler/dispatcher.py
Labels: bug

#445 fix: Handle missing kernel log gracefully
  changes/445.fix
  src/ai/backend/manager/api/session.py
Labels: bug

#448 fix: Standard-compliant GQL endpoint
  changes/448.fix
  src/ai/backend/manager/api/admin.py
  src/ai/backend/manager/server.py
Labels: API, bug

#447 fix: Regression of batch-type sessions
  changes/447.fix
  src/ai/backend/manager/api/session.py
  src/ai/backend/manager/registry.py
Labels: blocker, bug

#451 fix: Apply dataloader batching to Group.scaling_groups
  changes/451.fix
  src/ai/backend/manager/models/gql.py
  src/ai/backend/manager/models/group.py
  src/ai/backend/manager/models/scaling_group.py
Labels: bug

#452 fix: Revamp user group GQL queries
  changes/452.feature
  changes/452.fix
  src/ai/backend/manager/models/gql.py
  src/ai/backend/manager/models/group.py
Labels: bug, enhancement

#443 feat: Add a human readable error message for missing scaling groups
  changes/443.feature
  src/ai/backend/manager/registry.py
Labels: enhancement

#449 feat: Integrate queryfilter to all paginated list queries
  changes/449.breaking
  changes/449.feature
  setup.cfg
  src/ai/backend/manager/models/agent.py
  src/ai/backend/manager/models/gql.py
  src/ai/backend/manager/models/kernel.py
  src/ai/backend/manager/models/keypair.py
  src/ai/backend/manager/models/minilang/__init__.py
  src/ai/backend/manager/models/minilang/ordering.py
  src/ai/backend/manager/models/minilang/queryfilter.py
  src/ai/backend/manager/models/user.py
  src/ai/backend/manager/models/vfolder.py
  src/ai/backend/manager/server.py
  tests/test_queryfilter.py
  tests/test_queryorder.py
Labels: API, enhancement

#454 feat: add lock-related DB connection settings
  changes/454.feature
  src/ai/backend/manager/models/base.py
Labels: enhancement

#453 fix: Missing GQL root query field updates
  changes/453.fix
  src/ai/backend/manager/models/gql.py
  src/ai/backend/manager/models/kernel.py
  src/ai/backend/manager/models/keypair.py
  src/ai/backend/manager/models/minilang/ordering.py
  src/ai/backend/manager/models/storage.py
Labels: bug

#455 fix: Regression of session concurrency limit checks
  changes/455.fix
  src/ai/backend/manager/scheduler/predicates.py
Labels: blocker, bug

#456 fix: Partially revert #454 and fix wrong value
  changes/456.fix
  src/ai/backend/manager/models/base.py
Labels: blocker, bug

#457 fix: A hidden bug in the new batched resolvers for Group and ScalingGroup
  changes/457.fix
  src/ai/backend/manager/models/group.py
  src/ai/backend/manager/models/scaling_group.py
Labels: blocker, bug

#458 feat: make ilike operation is available in the queryfilter
  changes/458.feature
  src/ai/backend/manager/models/minilang/queryfilter.py
Labels: enhancement, minor

#459 fix: Value tranform with array values in queryfilter expr
  changes/459.fix
  src/ai/backend/manager/models/minilang/queryfilter.py
  src/ai/backend/manager/models/user.py
  tests/test_queryfilter.py
Labels: bug

#460 fix: Let the timeout idle checker skip batch-type sessions
  changes/460.fix
  src/ai/backend/manager/idle.py
Labels: bug

#463 fix: un-allocated resources were not excluded from the utilization criteria
  changes/463.fix
  src/ai/backend/manager/idle.py
Labels: bug

#462 setup: Update dependencies
  changes/462.misc
  setup.cfg
Labels: maintenance
