Repository lablup/backend.ai-manager, pull requests merged in 2021-06, with the labels that each got.

#435 feat: Add db transaction count tracker
  changes/435.feature
  src/ai/backend/manager/models/utils.py
Labels: enhancement

#437 feat: add access key into environment
  changes/437.feature
  src/ai/backend/manager/registry.py
Labels: feature, minor

#436 fix: Rewrite db connection mgmt for GraphQL resolvers and mutations
  changes/436.fix
  setup.cfg
  src/ai/backend/manager/api/admin.py
  src/ai/backend/manager/models/agent.py
  src/ai/backend/manager/models/base.py
  src/ai/backend/manager/models/domain.py
  src/ai/backend/manager/models/gql.py
  src/ai/backend/manager/models/group.py
  src/ai/backend/manager/models/kernel.py
  src/ai/backend/manager/models/keypair.py
  src/ai/backend/manager/models/resource_policy.py
  src/ai/backend/manager/models/resource_preset.py
  src/ai/backend/manager/models/scaling_group.py
  src/ai/backend/manager/models/user.py
  src/ai/backend/manager/models/utils.py
  src/ai/backend/manager/models/vfolder.py
Labels: blocker, bug, enhancement

#432 Feature/utilization based idle session checker
  changes/432.feature
  changes/432.fix
  src/ai/backend/manager/config.py
  src/ai/backend/manager/idle.py
Labels: feature

#434 fix: remain owner access key in session creation
  changes/433.feature
  changes/434.fix
  src/ai/backend/manager/api/session.py
  src/ai/backend/manager/api/utils.py
Labels: bug, minor

#439 fix: Initialization of error monitor plugin
  changes/439.fix
  src/ai/backend/manager/plugin/error_monitor.py
Labels: bug

#441 fix: do not collect data for utilization idle checker when interval is not passed
  changes/441.fix
  src/ai/backend/manager/idle.py
Labels: bug
