Repository lablup/backend.ai-manager, pull requests merged in 2021-04, with the labels that each got.

#416 fix: Remove no longer necessary isolation level
  changes/416.fix
  src/ai/backend/manager/scheduler/dispatcher.py
Labels: bug

#415 Rewrite scheduler to avoid HoL blocking
  changes/415.feature
  config/sample.etcd.config.json
  config/sample.volume.json
  src/ai/backend/manager/models/alembic/versions/8679d0a7e22b_add_scheduled_to_kernelstatus.py
  src/ai/backend/manager/models/kernel.py
  src/ai/backend/manager/registry.py
  src/ai/backend/manager/scheduler/__init__.py
  src/ai/backend/manager/scheduler/dispatcher.py
  src/ai/backend/manager/scheduler/drf.py
  src/ai/backend/manager/scheduler/fifo.py
  src/ai/backend/manager/scheduler/mof.py
  src/ai/backend/manager/scheduler/predicates.py
  src/ai/backend/manager/scheduler/types.py
  tests/test_scheduler.py
Labels: bug, maintenance

#418 fix: Adjust DoPrepareEvent firing rate
  changes/418.fix
  src/ai/backend/manager/distributed.py
  src/ai/backend/manager/scheduler/dispatcher.py
Labels: enhancement

#423 setup: Temporarily pin pytest-asyncio to 0.14.0 due to regression in handling event loops for fixtures
  changes/423.misc
  setup.cfg
Labels: maintenance

#427 Feature/#424 reflect username
  changes/424.feature
  src/ai/backend/manager/api/auth.py
Labels: bug, minor
