Repository lablup/backend.ai-manager, pull requests merged in 2021-03, with the labels that each got.

#402 fix: unable to fetch vfolders list
  changes/402.fix
  src/ai/backend/gateway/vfolder.py
Labels: bug

#403 fix: do not register sub containers to existing sessions if main container is TERMINATED
  changes/403.fix
  src/ai/backend/manager/scheduler/dispatcher.py
Labels: bug

#400 Refactor contextual shared objects to be statically typed in nested aiohttp apps
  changes/400.fix
  setup.cfg
  src/ai/backend/gateway/admin.py
  src/ai/backend/gateway/auth.py
  src/ai/backend/gateway/cluster_template.py
  src/ai/backend/gateway/config.py
  src/ai/backend/gateway/context.py
  src/ai/backend/gateway/domainconfig.py
  src/ai/backend/gateway/etcd.py
  src/ai/backend/gateway/events.py
  src/ai/backend/gateway/groupconfig.py
  src/ai/backend/gateway/image.py
  src/ai/backend/gateway/logs.py
  src/ai/backend/gateway/manager.py
  src/ai/backend/gateway/ratelimit.py
  src/ai/backend/gateway/resource.py
  src/ai/backend/gateway/scaling_group.py
  src/ai/backend/gateway/server.py
  src/ai/backend/gateway/session.py
  src/ai/backend/gateway/session_template.py
  src/ai/backend/gateway/stream.py
  src/ai/backend/gateway/types.py
  src/ai/backend/gateway/userconfig.py
  src/ai/backend/gateway/utils.py
  src/ai/backend/gateway/vfolder.py
  src/ai/backend/manager/cli/__main__.py
  src/ai/backend/manager/cli/etcd.py
  src/ai/backend/manager/models/agent.py
  src/ai/backend/manager/models/base.py
  src/ai/backend/manager/models/domain.py
  src/ai/backend/manager/models/gql.py
  src/ai/backend/manager/models/group.py
  src/ai/backend/manager/models/image.py
  src/ai/backend/manager/models/kernel.py
  src/ai/backend/manager/models/keypair.py
  src/ai/backend/manager/models/resource_policy.py
  src/ai/backend/manager/models/resource_preset.py
  src/ai/backend/manager/models/scaling_group.py
  src/ai/backend/manager/models/session_template.py
  src/ai/backend/manager/models/storage.py
  src/ai/backend/manager/models/user.py
  src/ai/backend/manager/models/vfolder.py
  src/ai/backend/manager/plugin/error_monitor.py
  src/ai/backend/manager/registry.py
  tests/conftest.py
  tests/gateway/test_auth.py
  tests/gateway/test_events.py
  tests/gateway/test_ratelimit.py
  tests/model_factory.py
Labels: feature

#404 fix: idle_timeout was not working due to last_access save error
  changes/404.fix
  src/ai/backend/gateway/config.py
  src/ai/backend/manager/idle.py
Labels: bug

#405 fix: missing pieces in #400
  changes/405.fix
  src/ai/backend/manager/models/gql.py
  src/ai/backend/manager/models/kernel.py
Labels: bug

#406 feat: Upgrade SQLAlchemy v1.4 for native asyncio support
  changes/406.fix
  config/ci.toml
  config/halfstack.toml
  config/sample.toml
  setup.cfg
  src/ai/backend/gateway/admin.py
  src/ai/backend/gateway/auth.py
  src/ai/backend/gateway/cluster_template.py
  src/ai/backend/gateway/context.py
  src/ai/backend/gateway/domainconfig.py
  src/ai/backend/gateway/events.py
  src/ai/backend/gateway/groupconfig.py
  src/ai/backend/gateway/image.py
  src/ai/backend/gateway/logs.py
  src/ai/backend/gateway/manager.py
  src/ai/backend/gateway/resource.py
  src/ai/backend/gateway/scaling_group.py
  src/ai/backend/gateway/server.py
  src/ai/backend/gateway/session.py
  src/ai/backend/gateway/session_template.py
  src/ai/backend/gateway/types.py
  src/ai/backend/gateway/userconfig.py
  src/ai/backend/gateway/utils.py
  src/ai/backend/gateway/vfolder.py
  src/ai/backend/manager/cli/fixture.py
  src/ai/backend/manager/idle.py
  src/ai/backend/manager/models/agent.py
  src/ai/backend/manager/models/base.py
  src/ai/backend/manager/models/domain.py
  src/ai/backend/manager/models/gql.py
  src/ai/backend/manager/models/group.py
  src/ai/backend/manager/models/image.py
  src/ai/backend/manager/models/kernel.py
  src/ai/backend/manager/models/keypair.py
  src/ai/backend/manager/models/minilang/queryfilter.py
  src/ai/backend/manager/models/resource_policy.py
  src/ai/backend/manager/models/resource_preset.py
  src/ai/backend/manager/models/scaling_group.py
  src/ai/backend/manager/models/session_template.py
  src/ai/backend/manager/models/user.py
  src/ai/backend/manager/models/utils.py
  src/ai/backend/manager/models/vfolder.py
  src/ai/backend/manager/plugin/error_monitor.py
  src/ai/backend/manager/registry.py
  src/ai/backend/manager/scheduler/__init__.py
  src/ai/backend/manager/scheduler/dispatcher.py
  src/ai/backend/manager/scheduler/predicates.py
  src/ai/backend/manager/types.py
  tests/conftest.py
  tests/manager/test_queryfilter.py
  tests/manager/test_registry.py
  tests/model_factory.py
Labels: feature

#407 fix: Add check for pgsql version to adjust connection args
  changes/407.fix
  src/ai/backend/gateway/auth.py
  src/ai/backend/gateway/server.py
  src/ai/backend/manager/models/base.py
  src/ai/backend/manager/models/vfolder.py
Labels: bug

#409 fix: Missing ref fix for gateway -> manager.api renaming
  changes/409.fix
  src/ai/backend/manager/container_registry/base.py
Labels: bug

#412 fix: Internal API mismatch for our custom SQLAlchemy enum types
  changes/412.fix
  setup.cfg
  src/ai/backend/manager/models/base.py
Labels: maintenance

#410 fix: Storage proxy URL example config
  changes/410.misc
  src/ai/backend/manager/config.py
Labels: maintenance

#411 refactor: Revise the manager CLI and promote generate-keypair command
  changes/411.fix
  src/ai/backend/manager/api/auth.py
  src/ai/backend/manager/cli/__main__.py
  src/ai/backend/manager/cli/context.py
  src/ai/backend/manager/server.py
Labels: maintenance

#413 fix: Regression in session/kernel cancellation and status updates
  changes/413.fix
  src/ai/backend/manager/registry.py
Labels: bug

#414 fix: Update sample configs
  changes/414.misc
  config/dev.shared.json
  config/sample.etcd.config.json
  config/sample.etcd.volumes.json
  fixtures/example-keypairs.json
  src/ai/backend/manager/config.py
Labels: maintenance
