Repository lablup/backend.ai-manager, pull requests merged in 2021-01, with the labels that each got.

#381 fix: Refresh the container registry config when rescanning
  changes/381.fix
  src/ai/backend/gateway/config.py
Labels: bug

#382 fix: Revert accidental code removal due to missing type annotation (partial revert of #381)
  changes/382.fix
  docs/382.fix
  src/ai/backend/gateway/config.py
  src/ai/backend/gateway/etcd.py
Labels: bug

#383 fix: cluster_idx in single-node sessions
  changes/383.fix
  src/ai/backend/gateway/session.py
Labels: bug

#384 Backport kernel creation bug fixes
  changes/373.fix
  changes/374.fix
  changes/384.breaking
  src/ai/backend/gateway/events.py
  src/ai/backend/gateway/session.py
  src/ai/backend/manager/registry.py
  src/ai/backend/manager/scheduler/dispatcher.py
Labels: bug

#385 fix: Add more indexes to reduce latency for cluster_role involving queries
  changes/385.feature
  src/ai/backend/manager/models/alembic/versions/518ecf41f567_add_index_for_cluster_role.py
  src/ai/backend/manager/models/kernel.py
Labels: feature

#386 fix: Improve shutdown stability using aiotools v1.2
  .github/workflows/timeline-check.yml
  changes/386.fix
  config/sample.shared.json
  setup.cfg
  src/ai/backend/gateway/server.py
Labels: bug

#387 fix: Regression in the idle timeout checker with session creation race fixes
  changes/387.fix
  src/ai/backend/manager/idle.py
Labels: bug

#389 feat: flashblade statistics implementation
  changes/389.feature
  src/ai/backend/manager/models/storage.py
Labels: API, feature

#388 fix: Improve handling of errors during cluster session creation and destruction
  changes/388.fix
  src/ai/backend/manager/models/agent.py
  src/ai/backend/manager/registry.py
  src/ai/backend/manager/scheduler/dispatcher.py
  src/ai/backend/manager/scheduler/predicates.py
Labels: bug

#390 setup: Update dependencies
  changes/390.fix
  setup.cfg
  src/ai/backend/gateway/auth.py
  src/ai/backend/gateway/events.py
  src/ai/backend/gateway/exceptions.py
  src/ai/backend/gateway/groupconfig.py
  src/ai/backend/manager/exceptions.py
  src/ai/backend/manager/idle.py
  src/ai/backend/manager/models/vfolder.py
  src/ai/backend/manager/registry.py
  src/ai/backend/manager/scheduler/dispatcher.py
  tests/manager/test_distributed.py
Labels: feature
