Repository lablup/backend.ai-manager, pull requests merged in 2021-08, with the labels that each got.

#466 fix: Improve missing vfolder error message
  changes/466.fix
  src/ai/backend/manager/registry.py
Labels: enhancement

#465 fix: Missing timestamp updates when terminating sessions
  changes/465.fix
  src/ai/backend/manager/registry.py
Labels: bug

#468 fix: return correct ID of the manager
  changes/468.fix
  src/ai/backend/manager/api/manager.py
Labels: bug, minor

#464 feat: Add queryfilter support for more columns
  changes/464.feature
  src/ai/backend/manager/models/kernel.py
  src/ai/backend/manager/models/keypair.py
  src/ai/backend/manager/models/user.py
Labels: enhancement

#470 setup: Explicitly specify SQLAlchemy's extra requirements
  changes/470.fix
  setup.cfg
Labels: bug

#475 feat: Add Etcd option to set MTU for the overlay networks of a cluster session
  changes/475.feature
  config/sample.etcd.config.json
  src/ai/backend/manager/config.py
  src/ai/backend/manager/registry.py
Labels: feature
