Repository lablup/backend.ai-manager, pull requests merged in 2021-02, with the labels that each got.

#392 Refactor event bus and related typing
  changes/392.fix
  src/ai/backend/gateway/cluster_template.py
  src/ai/backend/gateway/events.py
  src/ai/backend/gateway/logs.py
  src/ai/backend/gateway/server.py
  src/ai/backend/gateway/session.py
  src/ai/backend/gateway/stream.py
  src/ai/backend/manager/background.py
  src/ai/backend/manager/distributed.py
  src/ai/backend/manager/idle.py
  src/ai/backend/manager/models/error_logs.py
  src/ai/backend/manager/plugin/error_monitor.py
  src/ai/backend/manager/registry.py
  src/ai/backend/manager/scheduler/dispatcher.py
  src/ai/backend/manager/types.py
  tests/conftest.py
  tests/gateway/test_events.py
  tests/manager/test_distributed.py
  tests/manager/test_registry.py
Labels: feature

#395 fix: Explicitly use yaml.safe_load()
  changes/395.fix
  src/ai/backend/gateway/cluster_template.py
  src/ai/backend/gateway/config.py
  src/ai/backend/gateway/session_template.py
Labels: bug

#393 add: Append cloneable parameter for Vfolder cloning and updating options
  changes/393.feature
  src/ai/backend/gateway/vfolder.py
Labels: feature, minor

#394 fix: remove b-prefix in background task events function
  changes/394.fix
  src/ai/backend/gateway/events.py
Labels: minor

#397 feat: support renaming directories in vfolder
  changes/397.feature
  src/ai/backend/gateway/vfolder.py
Labels: API, minor

#398 setup: Update uvloop to 0.15 for better Python 3.8/3.9 support
  changes/398.fix
  setup.cfg
Labels: feature

#399 setup: Update pyzmq to 22.0.3
  changes/399.fix
  setup.cfg
  src/ai/backend/manager/registry.py
Labels: feature

#401 feat: add BACKENDAI_KERNEL_IMAGE environment variable in container
  changes/401.feature
  src/ai/backend/manager/registry.py
Labels: feature, minor
