Repository lablup/backend.ai-manager, pull requests merged in 2021-05, with the labels that each got.

#419 feat: share group virtual folder directly without invitation
  changes/419.feature
  src/ai/backend/manager/api/vfolder.py
  src/ai/backend/manager/models/vfolder.py
Labels: API, enhancement

#428 feat: unify global-default scheduler configs and per-scaling group scheduler options
  changes/428.feature
  src/ai/backend/manager/scheduler/dispatcher.py
Labels: blocker, enhancement

#421 fix: Remove num_queries counting to avoid excessive DB writes
  changes/421.fix
  src/ai/backend/manager/api/auth.py
  src/ai/backend/manager/models/keypair.py
  tests/api/test_auth.py
Labels: bug

#425 fix: Improve DB transaction hangs
  changes/425.fix
  src/ai/backend/manager/api/admin.py
  src/ai/backend/manager/api/auth.py
  src/ai/backend/manager/api/context.py
  src/ai/backend/manager/api/logs.py
  src/ai/backend/manager/api/resource.py
  src/ai/backend/manager/api/session.py
  src/ai/backend/manager/defs.py
  src/ai/backend/manager/idle.py
  src/ai/backend/manager/models/agent.py
  src/ai/backend/manager/models/gql.py
  src/ai/backend/manager/models/kernel.py
  src/ai/backend/manager/models/keypair.py
  src/ai/backend/manager/models/scaling_group.py
  src/ai/backend/manager/models/utils.py
  src/ai/backend/manager/registry.py
  src/ai/backend/manager/scheduler/dispatcher.py
  src/ai/backend/manager/scheduler/predicates.py
  src/ai/backend/manager/server.py
  tests/test_distributed.py
  tests/test_registry.py
Labels: blocker, bug

#430 fix: Prevent duplication of session-terminated events
  changes/430.fix
  src/ai/backend/manager/models/kernel.py
  src/ai/backend/manager/registry.py
Labels: bug

#420 feat: Add PRE_AUTH_MIDDLEWARE hook for auth with 3rd-party headers/cookies
  changes/420.feature
  fixtures/example-session-templates.json
  src/ai/backend/manager/api/auth.py
  src/ai/backend/manager/api/session.py
  src/ai/backend/manager/models/session_template.py
  tests/api/test_auth.py
  tests/api/test_ratelimit.py
Labels: enhancement

#433 feat: add BACKENDAI_SESSION_NAME envvar in session container
  changes/443.feature
  src/ai/backend/manager/registry.py
Labels: enhancement, minor
