Repository lablup/backend.ai-manager, pull requests merged in 2021-12, with the labels that each got.

#502 fix: Regression of stats API after applying asyncpg
  changes/502.fix
  src/ai/backend/manager/api/resource.py
Labels: bug, blocker, minor

#500 feat: add mutation query for agents table to update schedulable column
  changes/500.feature
  src/ai/backend/manager/models/agent.py
  src/ai/backend/manager/models/gql.py
Labels: feature, API, minor

#498 feat: Add "mgr clear-history" manager cli command
  changes/498.feature
  src/ai/backend/manager/cli/__main__.py
Labels: feature

#503 fix: Rollback polling of advisory lock in #483
  changes/503.fix
  src/ai/backend/manager/models/utils.py
Labels: bug, blocker

#479 feat: add start_service API
  changes/479.feature
  src/ai/backend/manager/api/scaling_group.py
  src/ai/backend/manager/api/session.py
  src/ai/backend/manager/models/alembic/versions/60a1effa77d2_add_coordinator_address_column_on_.py
  src/ai/backend/manager/models/scaling_group.py
Labels: feature, API, db-migration-required

#505 feat: Add support for session renaming
  changes/505.feature
  src/ai/backend/manager/api/session.py
Labels: API

#508 Update mypy to 0.930
  changes/508.fix
  setup.cfg
  src/ai/backend/manager/defs.py
  src/ai/backend/manager/distributed.py
  src/ai/backend/manager/models/base.py
  tests/test_advisory_lock.py
Labels: maintenance

#509 fix: Update typing using pyright
  changes/509.fix
  src/ai/backend/manager/api/events.py
  src/ai/backend/manager/api/session.py
  src/ai/backend/manager/api/stream.py
  src/ai/backend/manager/api/types.py
  src/ai/backend/manager/api/wsproxy.py
  src/ai/backend/manager/background.py
  src/ai/backend/manager/config.py
  src/ai/backend/manager/idle.py
  src/ai/backend/manager/models/domain.py
  src/ai/backend/manager/models/group.py
  src/ai/backend/manager/registry.py
  src/ai/backend/manager/scheduler/dispatcher.py
  src/ai/backend/manager/server.py
  tests/api/test_auth.py
Labels: maintenance
