Repository lablup/backend.ai-manager, pull requests merged in 2022-04, with the labels that each got.

#569 fix: remove invalid argument in `image_impl.py`
  changes/569.fix
  src/ai/backend/manager/cli/image_impl.py
Labels: bug

#570 refactor: Migrate distributed to common
  changes/570.fix.md
  src/ai/backend/manager/api/logs.py
  src/ai/backend/manager/distributed.py
  src/ai/backend/manager/idle.py
  src/ai/backend/manager/pglock.py
  src/ai/backend/manager/scheduler/dispatcher.py
  tests/test_distributed.py
Labels: refactor

#571 Replacible distributed lock backend
  changes/571.feature.md
  config/sample.toml
  setup.cfg
  src/ai/backend/manager/api/context.py
  src/ai/backend/manager/api/logs.py
  src/ai/backend/manager/cli/context.py
  src/ai/backend/manager/config.py
  src/ai/backend/manager/defs.py
  src/ai/backend/manager/idle.py
  src/ai/backend/manager/models/utils.py
  src/ai/backend/manager/pglock.py
  src/ai/backend/manager/scheduler/dispatcher.py
  src/ai/backend/manager/server.py
  src/ai/backend/manager/types.py
  tests/conftest.py
  tests/test_advisory_lock.py
  tests/test_scheduler.py
Labels: feature, refactor

#572 Migrate bgtask framework to common
  changes/572.fix.md
  setup.cfg
  src/ai/backend/manager/api/context.py
  src/ai/backend/manager/api/events.py
  src/ai/backend/manager/api/vfolder.py
  src/ai/backend/manager/background.py
  src/ai/backend/manager/container_registry/base.py
  src/ai/backend/manager/models/gql.py
  src/ai/backend/manager/models/image.py
  src/ai/backend/manager/server.py
  tests/conftest.py
Labels: refactor

#567 feat: Session lifecycle event callback as webhook
  changes/567.feature.md
  src/ai/backend/manager/api/session.py
  src/ai/backend/manager/models/alembic/versions/d727b5da20e6_add_callback_url_to_kernels.py
  src/ai/backend/manager/models/base.py
  src/ai/backend/manager/models/kernel.py
  src/ai/backend/manager/registry.py
  src/ai/backend/manager/server.py
Labels: feature, API

#568 feat: implement image metadata related GraphQL mutations
  changes/568.feature
  src/ai/backend/manager/models/base.py
  src/ai/backend/manager/models/gql.py
  src/ai/backend/manager/models/image.py
Labels: feature

#557 Add queryable parameters of vfolder and count project vfolder as well.
  changes/557.fix
  src/ai/backend/manager/models/vfolder.py
Labels: bug, refactor

#574 fix: rounded down resource not released after kernel creation
  changes/574.fix
  src/ai/backend/manager/registry.py
Labels: bug

#566 Add MIGRATION.md
  MIGRATION.md
  changes/566.misc.md
Labels: maintenance

#576 fix: remove duplicated logic to obtain redis local time in streaming proxy requests
  changes/576.fix
  src/ai/backend/manager/api/stream.py
Labels: bug

#578 fix: unable to update scaling group due to plain values of `scheduler_opts` are passed to the trafaret validation logic
  changes/578.fix
  src/ai/backend/manager/models/scaling_group.py
Labels: bug

#579 fix: remove explicit usage of advisory lock
  changes/579.fix
  src/ai/backend/manager/scheduler/dispatcher.py
Labels: bug

#577 fix: regression of the logic in getting the container stats per period
  changes/577.fix
  src/ai/backend/manager/api/resource.py
Labels: bug

#581 refactor: Separate use cases of URLNotFound and ObjectNotFound
  changes/581.fix.md
  src/ai/backend/manager/api/auth.py
  src/ai/backend/manager/api/events.py
  src/ai/backend/manager/api/exceptions.py
  src/ai/backend/manager/api/scaling_group.py
  src/ai/backend/manager/api/session.py
  src/ai/backend/manager/api/vfolder.py
  src/ai/backend/manager/models/gql.py
  src/ai/backend/manager/server.py
Labels: API, refactor

#582 refactor: Inherit ObjectNotFound errors
  changes/582.fix.md
  src/ai/backend/manager/api/exceptions.py
Labels: refactor

#583 feat: Add `KeyPairResourcePolicy.max_session_lifetime`
  changes/583.feature.md
  fixtures/example-keypairs.json
  src/ai/backend/manager/api/context.py
  src/ai/backend/manager/api/stream.py
  src/ai/backend/manager/config.py
  src/ai/backend/manager/idle.py
  src/ai/backend/manager/models/alembic/versions/81c264528f20_add_max_session_lifetime.py
  src/ai/backend/manager/models/resource_policy.py
  src/ai/backend/manager/scheduler/dispatcher.py
  src/ai/backend/manager/server.py
Labels: feature

#584 fix: do not create a session when memory is not larger than shared memory
  changes/584.fix
  src/ai/backend/manager/registry.py
Labels: bug
