Repository lablup/backend.ai-manager, pull requests merged in 2022-02, with the labels that each got.

#526 fix: prevent aioredis connection pool depletion in refrech_cb
  changes/526.fix
  src/ai/backend/manager/api/stream.py
Labels: bug

#516 feat: arbitrary path vfolder mounts
  changes/516.feature
  src/ai/backend/manager/api/session.py
  src/ai/backend/manager/defs.py
  src/ai/backend/manager/models/session_template.py
  tests/api/test_utils.py
Labels: feature

#531 fix: occupied slot not released when session creation fails
  changes/531.fix
  src/ai/backend/manager/scheduler/dispatcher.py
Labels: bug

#529 Further apply read-only txn hints
  changes/529.fix.md
  src/ai/backend/manager/api/auth.py
  src/ai/backend/manager/api/events.py
  src/ai/backend/manager/api/resource.py
  src/ai/backend/manager/api/session.py
  src/ai/backend/manager/api/utils.py
  src/ai/backend/manager/registry.py
Labels: refactor

#523 feat: Limit session types per scaling group
  changes/523.feature
  src/ai/backend/manager/models/base.py
  src/ai/backend/manager/models/scaling_group.py
  src/ai/backend/manager/scheduler/dispatcher.py
  src/ai/backend/manager/scheduler/predicates.py
Labels: feature, API

#534 setup: Upgrade callosum to resolve installation error on Ubuntu-20.04/aarch64
  changes/534.fix.md
  setup.cfg
Labels: maintenance

#517 fix: get_wsproxy_version raising GenericNotFound
  changes/517.fix
  src/ai/backend/manager/api/scaling_group.py
Labels: bug, API

#538 fix: Let `get_wsproxy_version()` be aware of per-user/per-group scaling group mapping
  changes/538.fix
  src/ai/backend/manager/api/scaling_group.py
Labels: bug

#540 fix: Wrong registry name in the sample etcd config
  changes/540.fix.md
  config/sample.etcd.config.json
Labels: bug

#533 fix: Ensure shutdown cancellation of shielded async tasks
  changes/533.feature
  src/ai/backend/manager/api/session.py
  src/ai/backend/manager/api/stream.py
  src/ai/backend/manager/api/wsproxy.py
Labels: refactor

#545 fix: correctly skip legacy docker hub kernel images (prefixed with `kernel-`)
  changes/545.fix
  src/ai/backend/manager/container_registry/docker.py
Labels: bug
