Repository lablup/backend.ai-manager, pull requests merged in 2022-05, with the labels that each got.

#586 ci: update mypy version to 0.950
  changes/586.fix
  setup.cfg
  src/ai/backend/manager/api/session.py
Labels: maintenance

#585 Include `group_id` params when getting allowed vfolder hosts
  changes/585.feature
  src/ai/backend/manager/api/vfolder.py
  src/ai/backend/manager/models/vfolder.py
Labels: feature

#589 fix: changes the default values of session options.
  changes/589.fix
  src/ai/backend/manager/api/session.py
Labels: bug, minor

#592 fix: Temporarily rollback the default distributed lock impl.
  changes/592.fix.md
  config/sample.toml
  src/ai/backend/manager/config.py
Labels: bug

#591 refactor: wrap `UnknownImageReference` as `ObjectNotFound`
  changes/591.feature
  src/ai/backend/manager/api/exceptions.py
  src/ai/backend/manager/api/session.py
Labels: help wanted, refactor

#588 fix: add automount folder when session creation occurs
  changes/588.fix
  src/ai/backend/manager/models/vfolder.py
Labels: bug, blocker, minor

#593 fix: Update `AbstractDistributedLock` import path
  changes/593.fix
  src/ai/backend/manager/pglock.py
  src/ai/backend/manager/types.py
Labels: maintenance

#594 fix: login session token (AIOHTTP_SESSION) is missing in start service API
  changes/594.fix
  src/ai/backend/manager/api/session.py
Labels: bug
