Repository lablup/backend.ai-manager, pull requests merged in 2022-03, with the labels that each got.

#530 fix: admins cannot terminate inactivated user's compute sessions
  changes/530.fix
  src/ai/backend/manager/api/utils.py
Labels: bug, minor

#542 fix: Don't allow empty values in allowed session types and scan all allowed scaling groups
  changes/542.fix
  src/ai/backend/manager/models/scaling_group.py
  src/ai/backend/manager/scheduler/predicates.py
  tests/test_predicates.py
Labels: bug

#546 setup: Upgrade aiotools to 1.5 series
  changes/546.misc.md
  setup.cfg
  src/ai/backend/manager/exceptions.py
Labels: maintenance

#547 fix: Generic DB error should not be retried except serialization failure
  changes/547.fix.md
  src/ai/backend/manager/models/utils.py
  src/ai/backend/manager/registry.py
  tests/models/test_dbutils.py
Labels: bug, blocker

#543 fix: image scan failing on multi architecture image
  changes/543.fix
  src/ai/backend/manager/cli/etcd.py
  src/ai/backend/manager/config.py
  src/ai/backend/manager/container_registry/base.py
Labels: bug

#544 feat: Allow superadmins to list vfolders as specific user
  changes/544.feature
  src/ai/backend/manager/api/utils.py
  src/ai/backend/manager/api/vfolder.py
Labels: feature

#548 feat: Add vfolder move-file API
  changes/548.feature.md
  src/ai/backend/manager/api/vfolder.py
  src/ai/backend/manager/models/storage.py
Labels: feature, API

#537 feat: Allow mounting vfolder subdirectory into session container
  changes/537.feature
  setup.cfg
  src/ai/backend/manager/api/image.py
  src/ai/backend/manager/api/session.py
  src/ai/backend/manager/models/__init__.py
  src/ai/backend/manager/models/alembic/versions/7dd1d81c3204_add_vfolder_mounts_to_kernels.py
  src/ai/backend/manager/models/base.py
  src/ai/backend/manager/models/dotfile.py
  src/ai/backend/manager/models/kernel.py
  src/ai/backend/manager/models/scaling_group.py
  src/ai/backend/manager/models/storage.py
  src/ai/backend/manager/models/vfolder.py
  src/ai/backend/manager/registry.py
  src/ai/backend/manager/scheduler/types.py
  src/ai/backend/manager/types.py
  tests/test_scheduler.py
Labels: feature

#549 fix: recent migration failure in trying to drop non-existing DB index
  changes/549.fix
  src/ai/backend/manager/models/alembic/versions/7dd1d81c3204_add_vfolder_mounts_to_kernels.py
Labels: bug, db-migration-required

#550 setup,ci: Set the required Python version to 3.10
  .github/workflows/default.yml
  .github/workflows/timeline-check.yml
  changes/550.breaking.md
  setup.cfg
  tests/api/test_middlewares.py
Labels: maintenance

#541 feature: add support for multi-arch image
  changes/541.feature
  setup.cfg
  src/ai/backend/manager/api/image.py
  src/ai/backend/manager/api/manager.py
  src/ai/backend/manager/api/session.py
  src/ai/backend/manager/api/vfolder.py
  src/ai/backend/manager/cli/__main__.py
  src/ai/backend/manager/cli/etcd.py
  src/ai/backend/manager/cli/image.py
  src/ai/backend/manager/cli/image_impl.py
  src/ai/backend/manager/config.py
  src/ai/backend/manager/container_registry/base.py
  src/ai/backend/manager/defs.py
  src/ai/backend/manager/models/agent.py
  src/ai/backend/manager/models/alembic/versions/015d84d5a5ef_add_image_table.py
  src/ai/backend/manager/models/alembic/versions/0f7a4b643940_.py
  src/ai/backend/manager/models/alembic/versions/911023380bc9_add_architecture_column_on_agents.py
  src/ai/backend/manager/models/base.py
  src/ai/backend/manager/models/gql.py
  src/ai/backend/manager/models/image.py
  src/ai/backend/manager/models/kernel.py
  src/ai/backend/manager/models/session_template.py
  src/ai/backend/manager/models/utils.py
  src/ai/backend/manager/registry.py
  src/ai/backend/manager/scheduler/dispatcher.py
  src/ai/backend/manager/scheduler/types.py
  tests/api/test_config.py
  tests/test_image.py
  tests/test_registry.py
  tests/test_scheduler.py
Labels: feature

#551 fix: give load aliases arg
  changes/551.fix
  src/ai/backend/manager/models/image.py
Labels: bug

#552 feat: add POST_AUTHORIZE notify hook
  changes/552.feature
  src/ai/backend/manager/api/auth.py
Labels: feature

#528 feat: Implement session dependencies
  changes/528.feature.md
  src/ai/backend/manager/api/session.py
  src/ai/backend/manager/registry.py
  src/ai/backend/manager/scheduler/predicates.py
  src/ai/backend/manager/server.py
Labels: feature

#553 fix: Missing replacement of connection with session for ORM query
  changes/553.fix
  src/ai/backend/manager/models/image.py
Labels: bug

#556 fix: Type errors found with new etcd module
  changes/566.fix.md
  src/ai/backend/manager/api/etcd.py
  src/ai/backend/manager/api/resource.py
  src/ai/backend/manager/api/stream.py
Labels: maintenance

#555 fix: Prevent hang upon daemon shutdown
  changes/555.fix.md
  setup.cfg
  src/ai/backend/manager/distributed.py
  src/ai/backend/manager/scheduler/dispatcher.py
  src/ai/backend/manager/server.py
Labels: bug

#558 fix: A long-standing, critical bug that leaked kernel creation tasks
  changes/558.fix.md
  src/ai/backend/manager/api/session.py
  src/ai/backend/manager/registry.py
Labels: bug, blocker

#554 fix: automatic round-down to quantum size
  changes/554.fix
  src/ai/backend/manager/models/image.py
  src/ai/backend/manager/registry.py
  src/ai/backend/manager/scheduler/dispatcher.py
  tests/test_registry.py
Labels: bug

#559 fix: Remove implicit trailing whitespace from the `agents.architecture` column
  changes/559.fix
  src/ai/backend/manager/models/agent.py
  src/ai/backend/manager/models/alembic/versions/11146ba02235_change_char_col_to_str.py
Labels: bug

#535 feat: migrate concurrency check to redis
  changes/535.feature
  fixtures/example-keypairs.json
  scripts/create-users-batch.py
  scripts/create-users-from-csv.py
  src/ai/backend/manager/api/auth.py
  src/ai/backend/manager/api/logs.py
  src/ai/backend/manager/api/manager.py
  src/ai/backend/manager/api/resource.py
  src/ai/backend/manager/api/session.py
  src/ai/backend/manager/api/vfolder.py
  src/ai/backend/manager/models/agent.py
  src/ai/backend/manager/models/alembic/versions/a7ca9f175d5f_merge.py
  src/ai/backend/manager/models/alembic/versions/d59ff89e7514_remove_keypair_concurrency_used.py
  src/ai/backend/manager/models/kernel.py
  src/ai/backend/manager/models/keypair.py
  src/ai/backend/manager/models/user.py
  src/ai/backend/manager/models/vfolder.py
  src/ai/backend/manager/registry.py
  src/ai/backend/manager/scheduler/dispatcher.py
  src/ai/backend/manager/scheduler/predicates.py
Labels: refactor

#561 fix: refer vfolder_mounts instead of will-be-deprecated mounts in returning session usage statistics
  changes/561.fix
  src/ai/backend/manager/api/resource.py
Labels: bug

#563 Do not `MSET` with empty updates in `recalculate_usage()`
  changes/563.fix
  src/ai/backend/manager/registry.py
Labels: bug

#527 Add an option to auto-cancel a pending session after specified timeout
  changes/527.feature
  src/ai/backend/manager/models/base.py
  src/ai/backend/manager/models/scaling_group.py
  src/ai/backend/manager/scheduler/dispatcher.py
  src/ai/backend/manager/scheduler/drf.py
  src/ai/backend/manager/scheduler/fifo.py
  src/ai/backend/manager/scheduler/mof.py
  src/ai/backend/manager/scheduler/predicates.py
  src/ai/backend/manager/scheduler/types.py
  tests/conftest.py
  tests/test_predicates.py
  tests/test_registry.py
  tests/test_scheduler.py
Labels: feature

#564 fix: let admins destroy and get the logs of a session by passing owner's access key in determining the access scope
  changes/564.fix
  src/ai/backend/manager/api/session.py
Labels: bug

#565 Add Redis persistent DB mgmt commands when clearing history
  changes/565.feature.md
  src/ai/backend/manager/cli/__main__.py
Labels: feature
