Repository lablup/backend.ai-manager, pull requests merged in 2022-01, with the labels that each got.

#504 feat: Move max_containers_per_session policy check from predicates
  changes/504.feature
  src/ai/backend/manager/api/session.py
  src/ai/backend/manager/registry.py
  src/ai/backend/manager/scheduler/predicates.py
Labels: refactor

#510 Fix potential hang-up issues while shutting down the service
  changes/510.fix.md
  src/ai/backend/manager/distributed.py
  src/ai/backend/manager/scheduler/dispatcher.py
  src/ai/backend/manager/server.py
  tests/test_distributed.py
Labels: bug

#513 fix: Use fixed event dispatcher node ID
  changes/513.fix.md
  config/sample.toml
  setup.cfg
  src/ai/backend/manager/config.py
  src/ai/backend/manager/server.py
  tests/test_distributed.py
Labels: bug, blocker

#514 fix: Improve kernel creation stability
  changes/514.fix.md
  setup.cfg
  src/ai/backend/manager/models/utils.py
  src/ai/backend/manager/registry.py
  src/ai/backend/manager/scheduler/predicates.py
  tests/api/test_events.py
Labels: bug

#518 fix: Further fixes for PREPARING/TERMINATING
  changes/518.fix.md
  setup.cfg
  src/ai/backend/manager/models/base.py
  src/ai/backend/manager/models/utils.py
  src/ai/backend/manager/registry.py
Labels: bug, blocker

#511 feat: Add mutation query for agents table to update scaling_group column
  changes/511.feature
  src/ai/backend/manager/models/agent.py
  src/ai/backend/manager/registry.py
Labels: feature

#512 misc: change the default values of max concurrent sessions and idle timeout in keypair fixture
  changes/512.misc
  fixtures/example-keypairs.json
Labels: minor, refactor

#519 fix: declare down_task in TCPProxy to prevent AttributeError
  changes/519.fix
  src/ai/backend/manager/api/wsproxy.py
Labels: bug

#522 fix: Reduce possibility of stuck in PREPARING under high-load conditions
  changes/522.fix.md
  src/ai/backend/manager/api/session.py
  src/ai/backend/manager/registry.py
  src/ai/backend/manager/scheduler/predicates.py
Labels: bug

#525 upstream: Migrate to aiodataloader-ng
  changes/525.fix.md
  setup.cfg
Labels: maintenance
